In [57]:
import pandas as pd
import numpy as np
import seaborn as sns

In [58]:
num_rows = 10

# Generate 10 unique ages (or a range)
ages = np.arange(20, 30) # Example: 20, 21, ..., 29

# Possible values for categorical columns
genders = ['Male', 'Female', 'Non-binary']
reviews = ['Excellent', 'Average', 'Poor']
educations = ['High School', 'Bachelor', 'Master', 'PhD', 'Associate']
purchased_options = ['Yes', 'No']

# Generate random data for other columns ensuring 10 entries
gender_data = np.random.choice(genders, num_rows, replace=True)
review_data = np.random.choice(reviews, num_rows, replace=True)
education_data = np.random.choice(educations, num_rows, replace=True)
purchased_data = np.random.choice(purchased_options, num_rows, replace=True)

# Create the DataFrame
data = {
    'age': ages,
    'gender': gender_data,
    'review': review_data,
    'education': education_data,
    'purchased': purchased_data
}

df = pd.DataFrame(data)
print(df)

   age      gender     review    education purchased
0   20  Non-binary       Poor     Bachelor        No
1   21        Male  Excellent          PhD       Yes
2   22        Male  Excellent     Bachelor       Yes
3   23        Male  Excellent     Bachelor        No
4   24  Non-binary       Poor          PhD       Yes
5   25  Non-binary    Average  High School        No
6   26      Female    Average     Bachelor        No
7   27        Male  Excellent       Master        No
8   28      Female       Poor     Bachelor       Yes
9   29  Non-binary  Excellent       Master       Yes

In [59]:
df.sample(5)

   age      gender     review    education purchased
5   25  Non-binary    Average  High School        No
0   20  Non-binary       Poor     Bachelor        No
9   29  Non-binary  Excellent       Master       Yes
8   28      Female       Poor     Bachelor       Yes
1   21        Male  Excellent          PhD       Yes

In [60]:
df = df[['review','education','purchased']]
df

      review    education purchased
0       Poor     Bachelor        No
1  Excellent          PhD       Yes
2  Excellent     Bachelor       Yes
3  Excellent     Bachelor        No
4       Poor          PhD       Yes
5    Average  High School        No
6    Average     Bachelor        No
7  Excellent       Master        No
8       Poor     Bachelor       Yes
9  Excellent       Master       Yes

In [61]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2)

In [62]:
x_train

      review    education
8       Poor     Bachelor
1  Excellent          PhD
5    Average  High School
3  Excellent     Bachelor
9  Excellent       Master
7  Excellent       Master
6    Average     Bachelor
0       Poor     Bachelor

In [63]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Excellent'],['High School','Bachelor','Master','PhD','Associate']])

In [64]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Excellent'],
                           ['High School', 'Bachelor', 'Master', 'PhD',
                            'Associate']])

In [65]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [66]:
x_train

array([[0., 1.],
       [2., 3.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [0., 1.]])

In [67]:
oe.categories

[['Poor', 'Average', 'Excellent'],
 ['High School', 'Bachelor', 'Master', 'PhD', 'Associate']]

In [68]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

LabelEncoder()

In [69]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [70]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [71]:
y_train,y_test

(array([1, 1, 0, 0, 1, 0, 0, 0]), array([1, 1]))

# One Hot Encoding

In [72]:
df = pd.read_csv("/content/car_price_prediction_.csv")

In [73]:
df.shape

(2500, 10)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Brand         2500 non-null   object
 2   Year          2500 non-null   int64
 3   Engine Size   2500 non-null   float64
 4   Fuel Type     2500 non-null   object
 5   Transmission  2500 non-null   object
 6   Mileage       2500 non-null   int64
 7   Condition     2500 non-null   object
 8   Price         2500 non-null   float64
 9   Model         2500 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 195.4+ KB

In [75]:
df.isnull().sum()

Car ID          0
Brand           0
Year            0
Engine Size     0
Fuel Type       0
Transmission    0
Mileage         0
Condition       0
Price           0
Model           0
dtype: int64

In [76]:
df.sample(5)

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
1474,1475,Honda,2004,2.1,Diesel,Manual,265332,Like New,67541.26,Fit
2251,2252,Toyota,2004,3.9,Hybrid,Manual,261025,New,68249.27,Camry
2205,2206,BMW,2022,4.9,Hybrid,Manual,215838,Like New,15072.58,5 Series
1260,1261,Audi,2016,1.4,Petrol,Manual,55152,Used,10557.62,Q5
349,350,BMW,2020,4.3,Electric,Manual,94515,Used,59300.95,3 Series

In [77]:
print(df['Fuel Type'].value_counts())
print(df['Transmission'].value_counts())

Fuel Type
Diesel      655
Petrol      630
Electric    614
Hybrid      601
Name: count, dtype: int64
Transmission
Manual       1308
Automatic    1192
Name: count, dtype: int64

##OneHotEncoding Using Pand

In [78]:
pd.get_dummies(df,columns=['Fuel Type','Condition'])

,Car ID,Brand,Year,Engine Size,Transmission,Mileage,Price,Model,Fuel Type_Diesel,Fuel Type_Electric,Fuel Type_Hybrid,Fuel Type_Petrol,Condition_Like New,Condition_New,Condition_Used
0,1,Tesla,2016,2.3,Manual,114832,26613.92,Model X,False,False,False,True,False,True,False
1,2,BMW,2018,4.4,Manual,143190,14679.61,5 Series,False,True,False,False,False,False,True
2,3,Audi,2013,4.5,Manual,181601,44402.61,A4,False,True,False,False,False,True,False
3,4,Tesla,2011,4.1,Automatic,68682,86374.33,Model Y,True,False,False,False,False,True,False
4,5,Ford,2009,2.6,Manual,223009,73577.10,Mustang,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,Audi,2020,2.4,Automatic,22650,61384.10,Q5,False,False,False,True,True,False,False
2496,2497,Audi,2001,5.7,Manual,77701,24710.35,A3,False,False,True,False,True,False,False
2497,2498,Ford,2021,1.1,Manual,272827,29902.45,Fiesta,False,False,True,False,True,False,False
2498,2499,Audi,2002,4.5,Manual,229164,46085.67,Q5,True,False,False,False,True,False,False
2499,2500,Toyota,2005,4.6,Automatic,80978,16594.14,RAV4,True,False,False,False,False,False,True

## 2.K-1 OneHot Encoding

In [79]:
pd.get_dummies(df,columns=['Fuel Type','Condition'],drop_first = True)

# Remove the first column of every onehot Encoding

,Car ID,Brand,Year,Engine Size,Transmission,Mileage,Price,Model,Fuel Type_Electric,Fuel Type_Hybrid,Fuel Type_Petrol,Condition_New,Condition_Used
0,1,Tesla,2016,2.3,Manual,114832,26613.92,Model X,False,False,True,True,False
1,2,BMW,2018,4.4,Manual,143190,14679.61,5 Series,True,False,False,False,True
2,3,Audi,2013,4.5,Manual,181601,44402.61,A4,True,False,False,True,False
3,4,Tesla,2011,4.1,Automatic,68682,86374.33,Model Y,False,False,False,True,False
4,5,Ford,2009,2.6,Manual,223009,73577.10,Mustang,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,Audi,2020,2.4,Automatic,22650,61384.10,Q5,False,False,True,False,False
2496,2497,Audi,2001,5.7,Manual,77701,24710.35,A3,False,True,False,False,False
2497,2498,Ford,2021,1.1,Manual,272827,29902.45,Fiesta,False,True,False,False,False
2498,2499,Audi,2002,4.5,Manual,229164,46085.67,Q5,False,False,False,False,False
2499,2500,Toyota,2005,4.6,Automatic,80978,16594.14,RAV4,False,False,False,False,True

## 3. OneHotEncoding  Using Sklearn

In [80]:
df = df[['Brand','Year','Fuel Type','Transmission','Mileage','Price']]
df.head()

   Brand  Year Fuel Type Transmission  Mileage     Price
0  Tesla  2016    Petrol       Manual   114832  26613.92
1    BMW  2018  Electric       Manual   143190  14679.61
2   Audi  2013  Electric       Manual   181601  44402.61
3  Tesla  2011    Diesel    Automatic    68682  86374.33
4   Ford  2009    Diesel       Manual   223009  73577.10

In [81]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state = 2)

In [82]:
x_test.head()

         Brand  Year Fuel Type Transmission
1310      Ford  2007    Diesel       Manual
2461  Mercedes  2008    Petrol    Automatic
1580      Ford  2007    Petrol    Automatic
1938     Tesla  2005    Petrol    Automatic
1124  Mercedes  2015    Petrol       Manual

In [83]:
from sklearn.preprocessing import OneHotEncoder

ohe =OneHotEncoder(drop='first',sparse_output = False,dtype = np.int32)

In [84]:
x_train_new = ohe.fit_transform(x_train[['Fuel Type','Transmission']])
# do train data fit and transform in one line
# then make new array to do two spacific column onehotencoding
# Then make the numpy array using "toarray()"

In [85]:
x_test_new = ohe.transform(x_test[['Fuel Type','Transmission']])
# do test data fit and transform in one line
# then make new array to do two spacific column onehotencoding
# Then make the numpy array using "toarray()"

In [86]:
np.hstack((x_train[['Brand','Year']].values,x_train_new)).shape
# get first two column and numpy array combine by hstack
# Then get shape to indetify it is valid or not to do train or test

(2000, 6)

## 3. OneHotEncoding With Top Categories

In [87]:
df['Brand'].nunique()
year = df[df['Year'] == 2010]

In [88]:
count = year['Brand'].value_counts()

In [89]:
repl = count[count <= 2].index

In [90]:
pd.get_dummies(df['Brand'].replace(repl,'uncommon')).sample(5)

       Audi    BMW   Ford  Honda  Mercedes  Tesla  Toyota
2242  False  False  False  False     False   True   False
1214  False   True  False  False     False  False   False
239   False  False   True  False     False  False   False
1426  False  False  False  False     False  False    True
669   False  False  False  False     False  False    True

In [91]:
print("""
After applying One-Hot Encoding:

Fuel Type column is converted into:
- Fuel_Type_Electric
- Fuel_Type_Hybrid
- Fuel_Type_Petrol

Transmission column is converted into:
- Transmission_Manual (Automatic is dropped due to drop_first=True)

Each column now contains True/False (or 1/0),
which machine learning models can understand.
""")

After applying One-Hot Encoding:

Fuel Type column is converted into:
- Fuel_Type_Electric
- Fuel_Type_Hybrid
- Fuel_Type_Petrol

Transmission column is converted into:
- Transmission_Manual (Automatic is dropped due to drop_first=True)

Each column now contains True/False (or 1/0),
which machine learning models can understand.

In [92]:
# Convert boolean to integer (True=1, False=0)
df = df.astype({col: 'int' for col in df.select_dtypes(include='bool').columns})

df.head()

   Brand  Year Fuel Type Transmission  Mileage     Price
0  Tesla  2016    Petrol       Manual   114832  26613.92
1    BMW  2018  Electric       Manual   143190  14679.61
2   Audi  2013  Electric       Manual   181601  44402.61
3  Tesla  2011    Diesel    Automatic    68682  86374.33
4   Ford  2009    Diesel       Manual   223009  73577.10

In [93]:
# Drop non-numeric columns (for ML preparation)
df_clean = df.drop(['Brand', 'Transmission'], axis=1)

df_clean.head()

   Year Fuel Type  Mileage     Price
0  2016    Petrol   114832  26613.92
1  2018  Electric   143190  14679.61
2  2013  Electric   181601  44402.61
3  2011    Diesel    68682  86374.33
4  2009    Diesel   223009  73577.10

In [94]:
print("Final Dataset Info:\n")
df_clean.info()

Final Dataset Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Year       2500 non-null   int64
 1   Fuel Type  2500 non-null   object
 2   Mileage    2500 non-null   int64
 3   Price      2500 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 78.3+ KB

In [96]:
# Select only numeric columns
df_numeric = df_clean.select_dtypes(include=['int64', 'float64'])

# Now apply correlation
corr = df_numeric.corr()

print(corr['Price'].sort_values(ascending=False))

Price      1.000000
Mileage   -0.008567
Year      -0.036805
Name: Price, dtype: float64

In [97]:
print("""
Conclusion:

1. Applied One-Hot Encoding on Fuel Type and Transmission
2. Converted boolean values into numeric format
3. Removed unnecessary text columns
4. Prepared dataset for Machine Learning
5. Performed basic analysis on Price

Now the dataset is ready for model training.
""")

Conclusion:

1. Applied One-Hot Encoding on Fuel Type and Transmission
2. Converted boolean values into numeric format
3. Removed unnecessary text columns
4. Prepared dataset for Machine Learning
5. Performed basic analysis on Price

Now the dataset is ready for model training.