In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/orders.csv',usecols = ['order_date','delivery_date'] )

In [3]:
df

    order_date delivery_date
0    2021-8-30    2021-09-24
1     2021-2-3    2021-02-13
2    2021-10-8    2021-11-03
3     2021-5-6    2021-05-19
4    2021-3-23    2021-03-24
..         ...           ...
995  2021-1-13    2021-02-02
996  2021-1-18    2021-01-31
997   2021-5-5    2021-05-21
998  2021-6-15    2021-07-12
999   2021-4-7    2021-04-24

[1000 rows x 2 columns]

In [4]:
df['Time'] = pd.to_datetime(
    np.random.randint(3600, 86400, len(df)),
    unit='s'
).time

In [5]:
df.head()

  order_date delivery_date      Time
0  2021-8-30    2021-09-24  19:41:44
1   2021-2-3    2021-02-13  10:16:51
2  2021-10-8    2021-11-03  19:50:31
3   2021-5-6    2021-05-19  02:04:54
4  2021-3-23    2021-03-24  03:43:06

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     1000 non-null   object
 1   delivery_date  1000 non-null   object
 2   Time           1000 non-null   object
dtypes: object(3)
memory usage: 23.6+ KB

In [7]:
df.isnull().sum()

order_date       0
delivery_date    0
Time             0
dtype: int64

In [8]:
df['order_date'] = df['order_date'].astype('datetime64[ns]')
df['delivery_date'] = df['delivery_date'].astype('datetime64[ns]')
df['Time'] = pd.to_datetime(df['Time'].astype(str))

/tmp/ipykernel_22174/3127246086.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['Time'].astype(str))

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     1000 non-null   datetime64[ns]
 1   delivery_date  1000 non-null   datetime64[ns]
 2   Time           1000 non-null   datetime64[ns]
dtypes: datetime64[ns](3)
memory usage: 23.6 KB

In [10]:
# extract Year
df['year'] = (df['order_date']).dt.year
df.head()

  order_date delivery_date                Time  year
0 2021-08-30    2021-09-24 2026-05-12 19:41:44  2021
1 2021-02-03    2021-02-13 2026-05-12 10:16:51  2021
2 2021-10-08    2021-11-03 2026-05-12 19:50:31  2021
3 2021-05-06    2021-05-19 2026-05-12 02:04:54  2021
4 2021-03-23    2021-03-24 2026-05-12 03:43:06  2021

In [11]:
# Extract Month
df['order_month'] = (df['order_date']).dt.month_name()
df['delivary_month'] = (df['delivery_date']).dt.month_name()
df.head()

,order_date,delivery_date,Time,year,order_month,delivary_month
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March

In [12]:
# Extract Day

df['order_day'] = (df['order_date']).dt.day
df['delivary_day'] = (df['delivery_date']).dt.day
df.head()

,order_date,delivery_date,Time,year,order_month,delivary_month,order_day,delivary_day
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September,30,24
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February,3,13
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November,8,3
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May,6,19
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March,23,24

In [13]:
# Which day of week when ordered and delivered
df['order_week_day'] = (df['order_date']).dt.dayofweek
df['delivary_week_day'] = (df['delivery_date']).dt.dayofweek
df.head()

,order_date,delivery_date,Time,year,order_month,delivary_month,order_day,delivary_day,order_week_day,delivary_week_day
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September,30,24,0,4
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February,3,13,2,5
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November,8,3,4,2
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May,6,19,3,2
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March,23,24,1,2

In [14]:
df['date_is_weekend_o'] = np.where(df['order_week_day'].isin([6,7]),1,0)
df['date_is_weekend_d'] = np.where(df['delivary_week_day'].isin([6,7]),1,0)
df.head(5)

,order_date,delivery_date,Time,year,order_month,delivary_month,order_day,delivary_day,order_week_day,delivary_week_day,date_is_weekend_o,date_is_weekend_d
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September,30,24,0,4,0,0
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February,3,13,2,5,0,0
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November,8,3,4,2,0,0
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May,6,19,3,2,0,0
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March,23,24,1,2,0,0

In [15]:
# Extract Week of the Day
df['date_week'] = df['order_date'].dt.isocalendar().week
df['date_week_d'] = df['delivery_date'].dt.isocalendar().week

df.head()

,order_date,delivery_date,Time,year,order_month,delivary_month,order_day,delivary_day,order_week_day,delivary_week_day,date_is_weekend_o,date_is_weekend_d,date_week,date_week_d
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September,30,24,0,4,0,0,35,38
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February,3,13,2,5,0,0,5,6
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November,8,3,4,2,0,0,40,44
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May,6,19,3,2,0,0,18,20
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March,23,24,1,2,0,0,12,12

In [16]:
# Extract Quater
df['quater'] = df['order_date'].dt.quarter
df['quater_d'] = df['delivery_date'].dt.quarter
df.head()

,order_date,delivery_date,Time,year,order_month,delivary_month,order_day,delivary_day,order_week_day,delivary_week_day,date_is_weekend_o,date_is_weekend_d,date_week,date_week_d,quater,quater_d
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September,30,24,0,4,0,0,35,38,3,3
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February,3,13,2,5,0,0,5,6,1,1
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November,8,3,4,2,0,0,40,44,4,4
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May,6,19,3,2,0,0,18,20,2,2
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March,23,24,1,2,0,0,12,12,1,1

In [17]:
# Extract Semester

df['semster_o'] = np.where(df['quater'].isin([1,2]),1,2)
df['semster_d'] = np.where(df['quater_d'].isin([1,2]),1,2)
df.head()

,order_date,delivery_date,Time,year,order_month,delivary_month,order_day,delivary_day,order_week_day,delivary_week_day,date_is_weekend_o,date_is_weekend_d,date_week,date_week_d,quater,quater_d,semster_o,semster_d
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September,30,24,0,4,0,0,35,38,3,3,2,2
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February,3,13,2,5,0,0,5,6,1,1,1,1
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November,8,3,4,2,0,0,40,44,4,4,2,2
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May,6,19,3,2,0,0,18,20,2,2,1,1
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March,23,24,1,2,0,0,12,12,1,1,1,1

In [18]:
# Difference between order and delivary

df['diff'] = df['delivery_date'] - df['order_date']
df.head()

,order_date,delivery_date,Time,year,order_month,delivary_month,order_day,delivary_day,order_week_day,delivary_week_day,date_is_weekend_o,date_is_weekend_d,date_week,date_week_d,quater,quater_d,semster_o,semster_d,diff
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September,30,24,0,4,0,0,35,38,3,3,2,2,25 days
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February,3,13,2,5,0,0,5,6,1,1,1,1,10 days
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November,8,3,4,2,0,0,40,44,4,4,2,2,26 days
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May,6,19,3,2,0,0,18,20,2,2,1,1,13 days
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March,23,24,1,2,0,0,12,12,1,1,1,1,1 days

In [19]:
# Month Passed
df['diff_month'] = (
    (df['delivery_date'].dt.year - df['order_date'].dt.year) * 12
    +
    (df['delivery_date'].dt.month - df['order_date'].dt.month)
)

df.head()

,order_date,delivery_date,Time,year,order_month,delivary_month,order_day,delivary_day,order_week_day,delivary_week_day,date_is_weekend_o,date_is_weekend_d,date_week,date_week_d,quater,quater_d,semster_o,semster_d,diff,diff_month
0,2021-08-30,2021-09-24,2026-05-12 19:41:44,2021,August,September,30,24,0,4,0,0,35,38,3,3,2,2,25 days,1
1,2021-02-03,2021-02-13,2026-05-12 10:16:51,2021,February,February,3,13,2,5,0,0,5,6,1,1,1,1,10 days,0
2,2021-10-08,2021-11-03,2026-05-12 19:50:31,2021,October,November,8,3,4,2,0,0,40,44,4,4,2,2,26 days,1
3,2021-05-06,2021-05-19,2026-05-12 02:04:54,2021,May,May,6,19,3,2,0,0,18,20,2,2,1,1,13 days,0
4,2021-03-23,2021-03-24,2026-05-12 03:43:06,2021,March,March,23,24,1,2,0,0,12,12,1,1,1,1,1 days,0

In [21]:
df1 = pd.to_datetime(df['Time'])
df1.head()

0   2026-05-12 19:41:44
1   2026-05-12 10:16:51
2   2026-05-12 19:50:31
3   2026-05-12 02:04:54
4   2026-05-12 03:43:06
Name: Time, dtype: datetime64[ns]

In [22]:
df1.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: Time
Non-Null Count  Dtype
--------------  -----
1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [24]:
df1 = pd.to_datetime(df1.astype(str))

In [25]:
df1

0     2026-05-12 19:41:44
1     2026-05-12 10:16:51
2     2026-05-12 19:50:31
3     2026-05-12 02:04:54
4     2026-05-12 03:43:06
              ...
995   2026-05-12 11:22:33
996   2026-05-12 22:21:22
997   2026-05-12 12:52:34
998   2026-05-12 12:36:54
999   2026-05-12 15:41:17
Name: Time, Length: 1000, dtype: datetime64[ns]