In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('/content/train.csv',usecols = ['Age','Pclass','Fare','Survived'])

In [ ]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [ ]:
df.isnull().mean() * 100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [ ]:
x = df.drop(columns = 'Survived')
y = df['Survived']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [ ]:
x_train.head()

     Pclass   Age     Fare
331       1  45.5  28.5000
733       2  23.0  13.0000
382       3  32.0   7.9250
704       3  26.0   7.8542
813       3   6.0  31.2750

In [ ]:
knn = KNNImputer(n_neighbors=10,weights = 'uniform')

x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [ ]:
pd.DataFrame(x_train_trf,columns = x_train.columns).head()

   Pclass   Age     Fare
0     1.0  45.5  28.5000
1     2.0  23.0  13.0000
2     3.0  32.0   7.9250
3     3.0  26.0   7.8542
4     3.0   6.0  31.2750

In [ ]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)

y_pred = lr.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.7486033519553073

In [ ]:
si = SimpleImputer(strategy='median')

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [ ]:
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)

y_pred2 = lr.predict(x_test_trf2)

accuracy_score(y_test,y_pred2)

0.7374301675977654