In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
df = pd.read_csv('/content/train.csv',usecols = ['Age','Fare','Survived'])

In [6]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [7]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [9]:
x_train.head()

      Age     Fare
331  45.5  28.5000
733  23.0  13.0000
382  32.0   7.9250
704  26.0   7.8542
813   6.0  31.2750

In [10]:
si = SimpleImputer()
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.transform(x_test)

In [11]:
lg = LogisticRegression()
lg.fit(x_train_trf,y_train)
y_pred = lg.predict(x_test_trf)

accuracy_score(y_pred,y_test)

0.6480446927374302

In [12]:
mi = MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [15]:
mi.features_

array([0])

In [16]:
x_train_missing = mi.transform(x_train)
x_test_missing = mi.transform(x_test)

In [18]:
x_train['age_Na'] = x_train_missing
x_test['age_Na'] = x_test_missing

In [19]:
x_train

      Age      Fare  age_Na
331  45.5   28.5000   False
733  23.0   13.0000   False
382  32.0    7.9250   False
704  26.0    7.8542   False
813   6.0   31.2750   False
..    ...       ...     ...
106  21.0    7.6500   False
270   NaN   31.0000    True
860  41.0   14.1083   False
435  14.0  120.0000   False
102  21.0   77.2875   False

[712 rows x 3 columns]

In [21]:
si = SimpleImputer()
x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [27]:
lg2 = LogisticRegression()
lg2.fit(x_train_trf2,y_train)

y_pred = lg2.predict(x_test_trf2)

accuracy_score(y_pred,y_test)

0.6368715083798883

## With Sklearn

In [31]:
si = SimpleImputer(add_indicator=True)
x_train = si.fit_transform(x_train)
x_test = si.transform(x_test)

In [35]:
Lg = LogisticRegression()

Lg.fit(x_train,y_train)

y_pred = Lg.predict(x_test)

accuracy_score(y_pred,y_test)

0.6368715083798883